import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, CalendarOff, Check, Clock3, ImagePlus, LockKeyhole, LogOut, MessageSquarePlus, Pencil, Plus, RotateCcw, Scissors, Send, Settings, Store, Trash2, UserMinus, UserPlus } from 'lucide-react';
import { ConfirmDialog, EmptyState, Field, Form, Modal, StatusBadge, Toggle, useToast } from '../../../components/UI';
import { useDemo } from '../../../store/DemoContext';
import type { DaySchedule, DemoException, ExceptionType, Plan, Service, StaffMember, ThemeMode, WeeklySchedule } from '../../../types';
import { DAY_NAMES, formatDate, todayKey, uid } from '../../../utils/date';
import type { PanelScreen } from '../panelTypes';

function LockedNotice({ text, goTo }: { text: string; goTo: (screen: PanelScreen) => void }) {
  return <div className="locked-notice"><span><LockKeyhole size={20} /></span><div><strong>Edición disponible con Plan Managed</strong><p>{text}</p></div><button className="button subtle" type="button" onClick={() => goTo('requests')}>Solicitar cambio</button><a className="text-link" href="/demo/managed">Ver Plan Managed</a></div>;
}

export function ServicesScreen({ plan, goTo }: { plan: Plan; goTo: (screen: PanelScreen) => void }) {
  const { data, update } = useDemo();
  const toast = useToast();
  const [editing, setEditing] = useState<Service | 'new' | null>(null);

  const toggle = (id: string, active: boolean) => {
    update((draft) => { const item = draft.services.find((service) => service.id === id); if (item) item.active = active; });
    toast(active ? 'Servicio activado en la web' : 'Servicio ocultado de la web');
  };

  return <div className="screen-stack"><section className="screen-intro"><div><h2>Servicios</h2><p>{plan === 'managed' ? 'Precios, tiempos y profesionales sincronizados con la web.' : 'Consulta el catálogo publicado para tus clientes.'}</p></div>{plan === 'managed' && <button className="button primary" type="button" onClick={() => setEditing('new')}><Plus size={18} /> Nuevo servicio</button>}</section>{plan === 'essential' && <LockedNotice text="Puedes consultar servicios, precios y duraciones; Marques Works realiza los cambios por ti." goTo={goTo} />}<section className="panel-card service-table"><div className="table-head"><span>Servicio</span><span>Duración</span><span>Precio</span><span>Profesionales</span><span>Estado</span><span /></div>{data.services.map((service) => { const workers = data.staff.filter((member) => member.serviceIds.includes(service.id)); return <article className={!service.active ? 'disabled-row' : ''} key={service.id}><div className="table-main"><span className="table-icon"><Scissors size={19} /></span><span><strong>{service.name}</strong><small>{service.description}</small></span></div><span data-label="Duración">{service.duration} min</span><strong data-label="Precio">{service.price.toFixed(2)} €</strong><span className="staff-mini-list" data-label="Profesionales">{workers.map((worker) => <b key={worker.id}>{worker.name.slice(0, 1)}</b>)}{!workers.length && <small>Sin asignar</small>}</span><span data-label="Estado">{plan === 'managed' ? <Toggle checked={service.active} onChange={(checked) => toggle(service.id, checked)} label={service.active ? 'Activo' : 'Inactivo'} /> : <span className={`availability ${service.active ? 'active' : ''}`}>{service.active ? 'Activo' : 'Inactivo'}</span>}</span>{plan === 'managed' && <button className="icon-button" type="button" onClick={() => setEditing(service)} aria-label={`Editar ${service.name}`}><Pencil size={17} /></button>}</article>; })}</section>{plan === 'managed' && <ServiceModal value={editing} onClose={() => setEditing(null)} />}</div>;
}

function ServiceModal({ value, onClose }: { value: Service | 'new' | null; onClose: () => void }) {
  const { data, update } = useDemo();
  const toast = useToast();
  const isNew = value === 'new';
  const original = value && value !== 'new' ? value : null;
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [price, setPrice] = useState(''); const [duration, setDuration] = useState('30'); const [staffIds, setStaffIds] = useState<string[]>([]); const [error, setError] = useState('');
  useEffect(() => { if (!value) return; setName(original?.name ?? ''); setDescription(original?.description ?? ''); setPrice(original ? String(original.price) : ''); setDuration(original ? String(original.duration) : '30'); setStaffIds(original ? data.staff.filter((member) => member.serviceIds.includes(original.id)).map((member) => member.id) : data.staff.map((member) => member.id)); setError(''); }, [value, original?.id]);
  const save = () => {
    const numericPrice = Number(price); const numericDuration = Number(duration);
    if (!name.trim() || !Number.isFinite(numericPrice) || numericPrice < 0 || !Number.isInteger(numericDuration) || numericDuration < 10 || numericDuration > 240) { setError('Indica un nombre, un precio válido y una duración entre 10 y 240 minutos.'); return; }
    const id = original?.id ?? uid('service');
    update((draft) => { if (original) { const service = draft.services.find((item) => item.id === original.id)!; Object.assign(service, { name: name.trim(), description: description.trim(), price: numericPrice, duration: numericDuration }); } else draft.services.push({ id, name: name.trim(), description: description.trim(), price: numericPrice, duration: numericDuration, active: true, image: '/images/barber-tools.webp' }); draft.staff.forEach((member) => { const has = member.serviceIds.includes(id); const should = staffIds.includes(member.id); if (should && !has) member.serviceIds.push(id); if (!should && has) member.serviceIds = member.serviceIds.filter((serviceId) => serviceId !== id); }); });
    toast(isNew ? 'Servicio creado y publicado' : 'Servicio actualizado en la web'); onClose();
  };
  return <Modal open={Boolean(value)} title={isNew ? 'Nuevo servicio' : 'Editar servicio'} onClose={onClose}><Form onSubmit={save} className="form-stack"><Field label="Nombre *"><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej. Corte clásico" /></Field><Field label="Descripción"><textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Una frase clara para el cliente" /></Field><div className="form-grid two"><Field label="Precio (€) *"><input type="number" min="0" step="0.5" value={price} onChange={(event) => setPrice(event.target.value)} /></Field><Field label="Duración (min) *"><input type="number" min="10" step="5" value={duration} onChange={(event) => setDuration(event.target.value)} /></Field></div><fieldset className="check-fieldset"><legend>Profesionales que lo realizan</legend>{data.staff.map((member) => <label key={member.id}><input type="checkbox" checked={staffIds.includes(member.id)} onChange={(event) => setStaffIds((current) => event.target.checked ? [...current, member.id] : current.filter((id) => id !== member.id))} /><span>{member.name}<small>{member.role}</small></span></label>)}</fieldset>{error && <p className="inline-error">{error}</p>}<div className="form-actions"><button className="button ghost" type="button" onClick={onClose}>Cancelar</button><button className="button primary" type="submit">Guardar cambios</button></div></Form></Modal>;
}

function ScheduleEditor({ schedule, onChange, readOnly = false }: { schedule: WeeklySchedule; onChange: (next: WeeklySchedule) => void; readOnly?: boolean }) {
  const changeDay = (day: number, recipe: (value: DaySchedule) => void) => { const next = structuredClone(schedule); recipe(next[day]); onChange(next); };
  return <div className="schedule-editor">{[1, 2, 3, 4, 5, 6, 0].map((day) => { const value = schedule[day]; return <article key={day} className={!value.open ? 'closed' : ''}><div className="schedule-day"><strong>{DAY_NAMES[day]}</strong>{readOnly ? <span>{value.open ? 'Abierto' : 'Cerrado'}</span> : <Toggle checked={value.open} onChange={(checked) => changeDay(day, (item) => { item.open = checked; if (checked && !item.intervals.length) item.intervals = [{ start: '09:00', end: '14:00' }]; })} label={value.open ? 'Abierto' : 'Cerrado'} />}</div>{value.open && <div className="interval-list">{value.intervals.map((interval, index) => <div className="interval-row" key={`${day}-${index}`}><input type="time" value={interval.start} disabled={readOnly} onChange={(event) => changeDay(day, (item) => { item.intervals[index].start = event.target.value; })} /><span>—</span><input type="time" value={interval.end} disabled={readOnly} onChange={(event) => changeDay(day, (item) => { item.intervals[index].end = event.target.value; })} />{!readOnly && <button className="icon-button" type="button" onClick={() => changeDay(day, (item) => { item.intervals.splice(index, 1); if (!item.intervals.length) item.open = false; })}><Trash2 size={16} /></button>}</div>)}{!readOnly && value.intervals.length < 3 && <button className="text-button" type="button" onClick={() => changeDay(day, (item) => { item.intervals.push({ start: '16:00', end: '20:00' }); })}><Plus size={16} /> Añadir intervalo</button>}</div>}</article>; })}</div>;
}

function validSchedule(schedule: WeeklySchedule) {
  return Object.values(schedule).every((day) => !day.open || (day.intervals.length > 0 && day.intervals.every((interval) => interval.start < interval.end) && day.intervals.every((interval, index) => index === 0 || day.intervals[index - 1].end <= interval.start)));
}

export function HoursScreen({ plan, goTo }: { plan: Plan; goTo: (screen: PanelScreen) => void }) {
  const { data, update } = useDemo(); const toast = useToast(); const [draft, setDraft] = useState<WeeklySchedule>(() => structuredClone(data.openingHours)); const [error, setError] = useState('');
  useEffect(() => setDraft(structuredClone(data.openingHours)), [data.openingHours]);
  const save = () => { if (!validSchedule(draft)) { setError('Revisa los intervalos: la hora de inicio debe ser anterior al fin y no pueden solaparse.'); return; } update((dataDraft) => { dataDraft.openingHours = structuredClone(draft); }); setError(''); toast('Horario actualizado; la disponibilidad pública ya ha cambiado'); };
  return <div className="screen-stack"><section className="screen-intro"><div><h2>Horario general</h2><p>Define cuándo puede recibir reservas el negocio.</p></div>{plan === 'managed' && <button className="button primary" type="button" onClick={save}><Check size={18} /> Guardar horario</button>}</section>{plan === 'essential' && <LockedNotice text="El horario está en modo lectura. Envíanos una solicitud y lo actualizaremos por ti." goTo={goTo} />}<section className="panel-card schedule-card"><div className="card-header"><div><h3>Semana habitual</h3><p>Los horarios de cada profesional también se tienen en cuenta.</p></div><Clock3 /></div><ScheduleEditor schedule={plan === 'managed' ? draft : data.openingHours} onChange={setDraft} readOnly={plan === 'essential'} />{error && <p className="inline-error">{error}</p>}{plan === 'managed' && <div className="mobile-save-bar"><button className="button primary full" type="button" onClick={save}>Guardar cambios</button></div>}</section></div>;
}

export function TeamScreen({ plan, goTo }: { plan: Plan; goTo: (screen: PanelScreen) => void }) {
  const { data, update } = useDemo(); const toast = useToast(); const [editing, setEditing] = useState<StaffMember | null>(null);
  const requestWorker = (type: 'Nuevo trabajador' | 'Eliminar trabajador', member?: StaffMember) => { update((draft) => draft.requests.unshift({ id: uid('req'), type, subject: member ? `Solicitud para eliminar a ${member.name}` : 'Solicitud de nuevo trabajador', description: member ? `Solicitamos retirar a ${member.name} del equipo publicado.` : 'Queremos añadir un nuevo profesional al equipo.', date: todayKey(), status: 'Nueva', plan: 'managed' })); toast('Solicitud enviada a Marques Works'); };
  return <div className="screen-stack"><section className="screen-intro"><div><h2>Equipo</h2><p>{plan === 'managed' ? 'Gestiona servicios y disponibilidad de los profesionales actuales.' : 'Consulta quién atiende cada servicio.'}</p></div>{plan === 'managed' && <button className="button subtle" type="button" onClick={() => requestWorker('Nuevo trabajador')}><UserPlus size={18} /> Solicitar nuevo trabajador</button>}</section>{plan === 'essential' && <LockedNotice text="La gestión de profesionales y disponibilidad se realiza mediante solicitud." goTo={goTo} />}<section className="staff-card-grid">{data.staff.map((member) => <article className="panel-card staff-admin-card" key={member.id}><div className="staff-admin-head"><img src={member.avatar} alt="" /><div><span>{member.role}</span><h3>{member.name}</h3><p>{member.bio}</p></div><span className={`availability ${member.active ? 'active' : ''}`}>{member.active ? 'Activo' : 'Inactivo'}</span></div><div className="staff-services"><span>Servicios</span><div>{member.serviceIds.map((id) => <b key={id}>{data.services.find((service) => service.id === id)?.name}</b>)}</div></div><footer>{plan === 'managed' ? <><button className="button subtle" type="button" onClick={() => setEditing(member)}><Settings size={17} /> Gestionar</button><button className="text-button danger-text" type="button" onClick={() => requestWorker('Eliminar trabajador', member)}><UserMinus size={16} /> Solicitar eliminación</button></> : <span><Clock3 size={16} /> Horario individual disponible</span>}</footer></article>)}</section>{editing && <StaffModal member={editing} onClose={() => setEditing(null)} />}</div>;
}

function StaffModal({ member, onClose }: { member: StaffMember; onClose: () => void }) {
  const { data, update } = useDemo(); const toast = useToast(); const [role, setRole] = useState(member.role); const [bio, setBio] = useState(member.bio); const [active, setActive] = useState(member.active); const [serviceIds, setServiceIds] = useState(member.serviceIds); const [schedule, setSchedule] = useState<WeeklySchedule>(() => structuredClone(member.workingHours)); const [error, setError] = useState('');
  const save = () => { if (!role.trim() || !validSchedule(schedule)) { setError('Indica el puesto y revisa que los intervalos de horario sean válidos.'); return; } update((draft) => { const target = draft.staff.find((item) => item.id === member.id)!; Object.assign(target, { role: role.trim(), bio: bio.trim(), active, serviceIds, workingHours: structuredClone(schedule) }); }); toast('Profesional actualizado; la web ya usa su nueva disponibilidad'); onClose(); };
  return <Modal open title={`Gestionar a ${member.name}`} onClose={onClose} wide><Form onSubmit={save} className="form-stack"><div className="form-grid two"><Field label="Puesto"><input value={role} onChange={(event) => setRole(event.target.value)} /></Field><div className="field"><span className="field-label">Disponibilidad pública</span><Toggle checked={active} onChange={setActive} label={active ? 'Activo' : 'Inactivo'} /></div></div><Field label="Descripción"><textarea rows={2} value={bio} onChange={(event) => setBio(event.target.value)} /></Field><fieldset className="check-fieldset"><legend>Servicios que realiza</legend>{data.services.map((service) => <label key={service.id}><input type="checkbox" checked={serviceIds.includes(service.id)} onChange={(event) => setServiceIds((current) => event.target.checked ? [...current, service.id] : current.filter((id) => id !== service.id))} /><span>{service.name}<small>{service.duration} min</small></span></label>)}</fieldset><div><h3 className="subheading">Horario individual</h3><ScheduleEditor schedule={schedule} onChange={setSchedule} /></div>{error && <p className="inline-error">{error}</p>}<div className="form-actions"><button className="button ghost" type="button" onClick={onClose}>Cancelar</button><button className="button primary" type="submit">Guardar cambios</button></div></Form></Modal>;
}

const exceptionLabels: Record<ExceptionType, string> = { staff_vacation: 'Vacaciones trabajador', business_closure: 'Cierre del negocio', block: 'Bloqueo puntual', special_hours: 'Horario excepcional' };

export function ExceptionsScreen({ plan, goTo }: { plan: Plan; goTo: (screen: PanelScreen) => void }) {
  const { data, update } = useDemo(); const toast = useToast(); const [editing, setEditing] = useState<DemoException | 'new' | null>(null); const [deleting, setDeleting] = useState<DemoException | null>(null);
  const remove = () => { if (!deleting) return; update((draft) => { draft.exceptions = draft.exceptions.filter((item) => item.id !== deleting.id); }); toast('Excepción eliminada; se ha recalculado la disponibilidad'); setDeleting(null); };
  return <div className="screen-stack"><section className="screen-intro"><div><h2>Vacaciones y cierres</h2><p>Las excepciones bloquean o ajustan automáticamente la reserva pública.</p></div>{plan === 'managed' && <button className="button primary" type="button" onClick={() => setEditing('new')}><Plus size={18} /> Nueva excepción</button>}</section>{plan === 'essential' && <LockedNotice text="Consulta las excepciones activas y solicita cualquier cambio a Marques Works." goTo={goTo} />}<section className="panel-card exception-list">{data.exceptions.length ? [...data.exceptions].sort((a, b) => a.startDate.localeCompare(b.startDate)).map((item) => <article key={item.id}><span className="exception-icon"><CalendarOff /></span><div><span>{exceptionLabels[item.type]}</span><h3>{item.reason}</h3><p>{formatDate(item.startDate)}{item.endDate !== item.startDate ? ` — ${formatDate(item.endDate)}` : ''}{item.startTime && ` · ${item.startTime}–${item.endTime}`}</p><small>{item.staffId ? `Afecta a ${data.staff.find((staff) => staff.id === item.staffId)?.name}` : 'Afecta a todo el negocio'}</small></div>{plan === 'managed' && <div className="row-actions"><button className="icon-button" type="button" onClick={() => setEditing(item)}><Pencil size={17} /></button><button className="icon-button danger-text" type="button" onClick={() => setDeleting(item)}><Trash2 size={17} /></button></div>}</article>) : <EmptyState icon={<CalendarOff />} title="Sin excepciones" text="No hay vacaciones, cierres ni bloqueos registrados." />}</section>{plan === 'managed' && <ExceptionModal value={editing} onClose={() => setEditing(null)} />}<ConfirmDialog open={Boolean(deleting)} title="Eliminar excepción" message="Los horarios afectados volverán a estar disponibles si no existe otro bloqueo." confirmLabel="Eliminar" destructive onConfirm={remove} onClose={() => setDeleting(null)} /></div>;
}

function ExceptionModal({ value, onClose }: { value: DemoException | 'new' | null; onClose: () => void }) {
  const { data, update } = useDemo(); const toast = useToast(); const original = value && value !== 'new' ? value : null; const [type, setType] = useState<ExceptionType>('staff_vacation'); const [staffId, setStaffId] = useState('alex'); const [startDate, setStartDate] = useState(todayKey()); const [endDate, setEndDate] = useState(todayKey()); const [startTime, setStartTime] = useState(''); const [endTime, setEndTime] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!value) return; setType(original?.type ?? 'staff_vacation'); setStaffId(original?.staffId ?? data.staff[0]?.id ?? ''); setStartDate(original?.startDate ?? todayKey()); setEndDate(original?.endDate ?? todayKey()); setStartTime(original?.startTime ?? ''); setEndTime(original?.endTime ?? ''); setReason(original?.reason ?? ''); setError(''); }, [value, original?.id]);
  const needsStaff = type === 'staff_vacation' || type === 'block'; const usesTime = type === 'block' || type === 'special_hours';
  const save = () => { if (!reason.trim() || !startDate || !endDate || startDate > endDate || (needsStaff && !staffId) || (usesTime && ((!startTime || !endTime) || startTime >= endTime))) { setError('Revisa el motivo, el rango de fechas y las horas indicadas.'); return; } const next: DemoException = { id: original?.id ?? uid('exception'), type, ...(needsStaff ? { staffId } : {}), startDate, endDate, ...(usesTime ? { startTime, endTime } : {}), reason: reason.trim() }; update((draft) => { if (original) draft.exceptions = draft.exceptions.map((item) => item.id === original.id ? next : item); else draft.exceptions.push(next); }); toast('Excepción guardada; la disponibilidad se ha recalculado'); onClose(); };
  return <Modal open={Boolean(value)} title={original ? 'Editar excepción' : 'Nueva excepción'} onClose={onClose}><Form onSubmit={save} className="form-stack"><Field label="Tipo *"><select value={type} onChange={(event) => setType(event.target.value as ExceptionType)}>{Object.entries(exceptionLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>{needsStaff && <Field label="Profesional *"><select value={staffId} onChange={(event) => setStaffId(event.target.value)}>{data.staff.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></Field>}<div className="form-grid two"><Field label="Fecha inicio *"><input type="date" value={startDate} onChange={(event) => { setStartDate(event.target.value); if (event.target.value > endDate) setEndDate(event.target.value); }} /></Field><Field label="Fecha fin *"><input type="date" min={startDate} value={endDate} onChange={(event) => setEndDate(event.target.value)} /></Field></div>{usesTime && <div className="form-grid two"><Field label="Hora inicio *"><input type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} /></Field><Field label="Hora fin *"><input type="time" value={endTime} onChange={(event) => setEndTime(event.target.value)} /></Field></div>}<Field label="Motivo *"><input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ej. Vacaciones, festivo, formación…" /></Field>{error && <p className="inline-error">{error}</p>}<div className="form-actions"><button className="button ghost" type="button" onClick={onClose}>Cancelar</button><button className="button primary" type="submit">Guardar excepción</button></div></Form></Modal>;
}

const galleryPresets = [
  { image: '/images/barbershop-interior.webp', title: 'Sillón clásico' },
  { image: '/images/grooming-products.webp', title: 'Productos' },
  { image: '/images/hero-barber.webp', title: 'Acabado' },
];

export function GalleryScreen({ plan, goTo }: { plan: Plan; goTo: (screen: PanelScreen) => void }) {
  const { data, update } = useDemo(); const toast = useToast();
  const mutate = (id: string, action: 'up' | 'down' | 'toggle' | 'remove') => { update((draft) => { const ordered = [...draft.gallery].sort((a, b) => a.order - b.order); const index = ordered.findIndex((item) => item.id === id); if (index < 0) return; if (action === 'remove') draft.gallery = draft.gallery.filter((item) => item.id !== id); else if (action === 'toggle') ordered[index].active = !ordered[index].active; else { const target = action === 'up' ? index - 1 : index + 1; if (target >= 0 && target < ordered.length) [ordered[index], ordered[target]] = [ordered[target], ordered[index]]; } ordered.forEach((item, order) => { item.order = order; }); }); toast(action === 'remove' ? 'Imagen eliminada' : 'Galería actualizada en la web'); };
  const add = () => { const used = new Set(data.gallery.map((item) => item.image)); const preset = galleryPresets.find((item) => !used.has(item.image)) ?? galleryPresets[data.gallery.length % galleryPresets.length]; update((draft) => draft.gallery.push({ id: uid('gallery'), ...preset, active: true, order: draft.gallery.length })); toast('Imagen de demostración añadida'); };
  return <div className="screen-stack"><section className="screen-intro"><div><h2>Galería</h2><p>Organiza las imágenes que se muestran en la web pública.</p></div>{plan === 'managed' && <button className="button primary" type="button" onClick={add}><ImagePlus size={18} /> Añadir imagen demo</button>}</section>{plan === 'essential' && <LockedNotice text="La galería se gestiona con Plan Managed o mediante una solicitud de cambio." goTo={goTo} />}<section className="gallery-admin-grid">{[...data.gallery].sort((a, b) => a.order - b.order).map((item, index) => <article className={`panel-card gallery-admin-item ${!item.active ? 'inactive' : ''}`} key={item.id}><img src={item.image} alt={item.title} /><div><span>Posición {index + 1}</span><h3>{item.title}</h3></div>{plan === 'managed' && <><Toggle checked={item.active} onChange={() => mutate(item.id, 'toggle')} label={item.active ? 'Visible' : 'Oculta'} /><footer><button className="icon-button" type="button" disabled={index === 0} onClick={() => mutate(item.id, 'up')}><ArrowUp size={17} /></button><button className="icon-button" type="button" disabled={index === data.gallery.length - 1} onClick={() => mutate(item.id, 'down')}><ArrowDown size={17} /></button><button className="icon-button danger-text" type="button" onClick={() => mutate(item.id, 'remove')}><Trash2 size={17} /></button></footer></>}</article>)}</section></div>;
}

export function BusinessScreen({ plan, goTo }: { plan: Plan; goTo: (screen: PanelScreen) => void }) {
  const { data, update } = useDemo(); const toast = useToast(); const [draft, setDraft] = useState(data.business); useEffect(() => setDraft(data.business), [data.business]); const set = (key: keyof typeof draft, value: string) => setDraft((current) => ({ ...current, [key]: value })); const save = () => { if (!draft.name.trim() || !draft.phone.trim() || !draft.address.trim()) return; update((dataDraft) => { dataDraft.business = { ...draft }; }); toast('Datos publicados actualizados'); };
  return <div className="screen-stack"><section className="screen-intro"><div><h2>Datos del negocio</h2><p>La información visible en la web pública y los canales de contacto.</p></div>{plan === 'managed' && <button className="button primary" type="button" onClick={save}><Check size={18} /> Guardar cambios</button>}</section>{plan === 'essential' && <LockedNotice text="Consulta tus datos publicados y solicita cualquier modificación." goTo={goTo} />}<section className="panel-card business-form"><div className="form-section-title"><Store /><div><h3>Información pública</h3><p>Estos datos aparecen en la web de la barbería.</p></div></div><div className="form-grid two"><Field label="Nombre público"><input disabled={plan === 'essential'} value={draft.name} onChange={(event) => set('name', event.target.value)} /></Field><Field label="Email"><input disabled={plan === 'essential'} type="email" value={draft.email} onChange={(event) => set('email', event.target.value)} /></Field><Field label="Teléfono"><input disabled={plan === 'essential'} value={draft.phone} onChange={(event) => set('phone', event.target.value)} /></Field><Field label="WhatsApp"><input disabled={plan === 'essential'} value={draft.whatsapp} onChange={(event) => set('whatsapp', event.target.value)} /></Field><Field label="Dirección"><input disabled={plan === 'essential'} value={draft.address} onChange={(event) => set('address', event.target.value)} /></Field><Field label="Instagram"><input disabled={plan === 'essential'} value={draft.instagram} onChange={(event) => set('instagram', event.target.value)} /></Field><Field label="Facebook"><input disabled={plan === 'essential'} value={draft.facebook} onChange={(event) => set('facebook', event.target.value)} /></Field><Field label="Descripción"><textarea disabled={plan === 'essential'} rows={4} value={draft.description} onChange={(event) => set('description', event.target.value)} /></Field></div>{plan === 'managed' && <div className="mobile-save-bar"><button className="button primary full" type="button" onClick={save}>Guardar cambios</button></div>}</section></div>;
}

const requestTypes = {
  managed: ['Nuevo trabajador', 'Eliminar trabajador', 'Cambio de diseño', 'Nueva sección web', 'Problema técnico', 'Otro'],
  essential: ['Cambiar precio', 'Cambiar horario', 'Añadir trabajador', 'Cambiar fotografías', 'Cambiar información', 'Otro'],
};

export function RequestsScreen({ plan }: { plan: Plan }) {
  const { data, update } = useDemo(); const toast = useToast(); const [open, setOpen] = useState(false); const [type, setType] = useState(requestTypes[plan][0]); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState(''); const requests = data.requests.filter((item) => item.plan === plan).sort((a, b) => b.date.localeCompare(a.date));
  const save = () => { if (!subject.trim() || description.trim().length < 10) { setError('Añade un asunto y una descripción de al menos 10 caracteres.'); return; } update((draft) => draft.requests.unshift({ id: uid('req'), type, subject: subject.trim(), description: description.trim(), date: todayKey(), status: 'Nueva', plan })); toast('Solicitud enviada a Marques Works'); setOpen(false); setSubject(''); setDescription(''); setError(''); };
  return <div className="screen-stack"><section className="screen-intro"><div><h2>Solicitudes</h2><p>{plan === 'managed' ? 'Pide cambios que requieren intervención de Marques Works.' : 'Nos ocupamos de los cambios que no editas desde tu plan.'}</p></div><button className="button primary" type="button" onClick={() => setOpen(true)}><MessageSquarePlus size={18} /> Nueva solicitud</button></section>{plan === 'essential' && <div className="essential-explainer"><span><LockKeyhole /></span><div><strong>Gestión asistida incluida</strong><p>Cuéntanos qué necesitas cambiar y quedará registrado para que Marques Works lo gestione.</p></div></div>}<section className="panel-card request-list">{requests.length ? requests.map((request) => <article key={request.id}><span className="request-icon"><Send /></span><div><span>{request.type} · {formatDate(request.date, { day: 'numeric', month: 'short', year: 'numeric' })}</span><h3>{request.subject}</h3><p>{request.description}</p></div><StatusBadge status={request.status} /></article>) : <EmptyState icon={<MessageSquarePlus />} title="Sin solicitudes" text="Cuando necesites ayuda o un cambio, aparecerá aquí." />}</section><Modal open={open} title="Nueva solicitud" onClose={() => setOpen(false)}><Form onSubmit={save} className="form-stack"><Field label="Tipo *"><select value={type} onChange={(event) => setType(event.target.value)}>{requestTypes[plan].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Asunto *"><input value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Resume lo que necesitas" /></Field><Field label="Descripción *"><textarea rows={5} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Incluye los detalles necesarios para poder ayudarte…" /></Field>{error && <p className="inline-error">{error}</p>}<div className="form-actions"><button className="button ghost" type="button" onClick={() => setOpen(false)}>Cancelar</button><button className="button primary" type="submit"><Send size={17} /> Enviar solicitud</button></div></Form></Modal></div>;
}

export function SettingsScreen({ plan, onLogout }: { plan: Plan; onLogout: () => void }) {
  const { data, reset, setTheme } = useDemo(); const toast = useToast(); const [confirmReset, setConfirmReset] = useState(false); const themes: { value: ThemeMode; label: string; text: string }[] = [{ value: 'light', label: 'Claro', text: 'Interfaz luminosa' }, { value: 'dark', label: 'Oscuro', text: 'Menos brillo' }, { value: 'system', label: 'Sistema', text: 'Sigue tu dispositivo' }];
  const doReset = () => { reset(); setConfirmReset(false); toast('Datos de demostración restablecidos'); };
  return <div className="screen-stack"><section className="screen-intro"><div><h2>Configuración</h2><p>Preferencias del panel y herramientas para presentar la demo.</p></div></section><section className="panel-card settings-section"><div className="settings-title"><Settings /><div><h3>Apariencia</h3><p>La web pública mantiene siempre su diseño oscuro.</p></div></div><div className="theme-grid">{themes.map((theme) => <button className={data.settings.theme === theme.value ? 'active' : ''} type="button" key={theme.value} onClick={() => { setTheme(theme.value); toast(`Tema ${theme.label.toLowerCase()} aplicado`); }}><span className={`theme-preview ${theme.value}`}><i /><b /><em /></span><strong>{theme.label}</strong><small>{theme.text}</small>{data.settings.theme === theme.value && <Check size={17} />}</button>)}</div></section><section className="panel-card settings-section"><div className="settings-title"><RotateCcw /><div><h3>Datos de demostración</h3><p>Deja la aplicación limpia antes de enseñársela a otro cliente.</p></div></div><div className="danger-zone"><div><strong>Restablecer demo</strong><p>Borra citas, cambios, solicitudes y preferencias creadas durante la prueba. Recupera los datos iniciales dinámicos.</p></div><button className="button danger-ghost" type="button" onClick={() => setConfirmReset(true)}><RotateCcw size={17} /> Restablecer datos</button></div></section><section className="panel-card settings-section"><div className="settings-title"><Store /><div><h3>Cuenta de demostración</h3><p>MW BarberShop · Plan {plan === 'managed' ? 'Managed' : 'Essential'}</p></div></div><button className="button subtle" type="button" onClick={onLogout}><LogOut size={17} /> Cerrar sesión</button></section><ConfirmDialog open={confirmReset} title="¿Restablecer toda la demo?" message="Se perderán todos los cambios guardados en este navegador y se cargarán de nuevo los datos de ejemplo." confirmLabel="Sí, restablecer" destructive onConfirm={doReset} onClose={() => setConfirmReset(false)} /></div>;
}
